# Generated by Django 5.0.1 on 2025-01-14 11:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SpamReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("reported_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spam_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "spam_reports",
                "ordering": ["-reported_at"],
                "indexes": [
                    models.Index(
                        fields=["phone_number", "is_active"],
                        name="spam_report_phone_n_093a94_idx",
                    ),
                    models.Index(
                        fields=["reporter", "phone_number", "is_active"],
                        name="spam_report_reporte_73c4e1_idx",
                    ),
                    models.Index(
                        fields=["reported_at", "is_active"],
                        name="spam_report_reporte_3740b9_idx",
                    ),
                ],
                "unique_together": {("reporter", "phone_number")},
            },
        ),
    ]
